// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaySimple.HotelService.Data;

#nullable disable

namespace StaySimple.HotelService.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260318174008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StaySimple.HotelService.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Marine Drive, Mumbai",
                            City = "Mumbai",
                            Description = "A luxurious 5-star hotel overlooking the Arabian Sea with world-class amenities.",
                            ImageUrl = "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
                            Name = "The Grand Palace",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Palace Road, Jaipur",
                            City = "Jaipur",
                            Description = "Experience royal Rajasthani hospitality in this beautifully restored heritage property.",
                            ImageUrl = "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
                            Name = "Royal Heritage Inn",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 3,
                            Address = "78 Mall Road, Manali",
                            City = "Manali",
                            Description = "A serene mountain retreat with stunning Himalayan views and cozy accommodations.",
                            ImageUrl = "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
                            Name = "Mountain View Resort",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 4,
                            Address = "22 Baga Beach Road, Goa",
                            City = "Goa",
                            Description = "A beachfront paradise with private beach access and vibrant nightlife nearby.",
                            ImageUrl = "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
                            Name = "Sunset Beach Hotel",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 5,
                            Address = "99 Connaught Place, Delhi",
                            City = "Delhi",
                            Description = "Modern business hotel in the heart of New Delhi, perfect for work and leisure.",
                            ImageUrl = "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800",
                            Name = "City Central Hotel",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 6,
                            Address = "12 Lake Pichola Road, Udaipur",
                            City = "Udaipur",
                            Description = "A romantic lakeside hotel with stunning views of Lake Pichola and City Palace.",
                            ImageUrl = "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
                            Name = "Lakeside Retreat",
                            Rating = 4.7000000000000002
                        });
                });

            modelBuilder.Entity("StaySimple.HotelService.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1,
                            HotelId = 1,
                            IsAvailable = true,
                            PricePerNight = 3500m,
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            HotelId = 1,
                            IsAvailable = true,
                            PricePerNight = 5500m,
                            RoomType = "Double"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            HotelId = 1,
                            IsAvailable = true,
                            PricePerNight = 12000m,
                            RoomType = "Suite"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 1,
                            HotelId = 2,
                            IsAvailable = true,
                            PricePerNight = 2500m,
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 2,
                            HotelId = 2,
                            IsAvailable = true,
                            PricePerNight = 4000m,
                            RoomType = "Double"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 3,
                            HotelId = 2,
                            IsAvailable = true,
                            PricePerNight = 7500m,
                            RoomType = "Deluxe"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 1,
                            HotelId = 3,
                            IsAvailable = true,
                            PricePerNight = 2000m,
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 2,
                            HotelId = 3,
                            IsAvailable = true,
                            PricePerNight = 3500m,
                            RoomType = "Double"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 4,
                            HotelId = 3,
                            IsAvailable = true,
                            PricePerNight = 6000m,
                            RoomType = "Suite"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 1,
                            HotelId = 4,
                            IsAvailable = true,
                            PricePerNight = 3000m,
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 2,
                            HotelId = 4,
                            IsAvailable = true,
                            PricePerNight = 5000m,
                            RoomType = "Double"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 3,
                            HotelId = 4,
                            IsAvailable = true,
                            PricePerNight = 8500m,
                            RoomType = "Deluxe"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 1,
                            HotelId = 5,
                            IsAvailable = true,
                            PricePerNight = 2200m,
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 2,
                            HotelId = 5,
                            IsAvailable = true,
                            PricePerNight = 3800m,
                            RoomType = "Double"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 2,
                            HotelId = 6,
                            IsAvailable = true,
                            PricePerNight = 4500m,
                            RoomType = "Double"
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 4,
                            HotelId = 6,
                            IsAvailable = true,
                            PricePerNight = 9500m,
                            RoomType = "Suite"
                        });
                });

            modelBuilder.Entity("StaySimple.HotelService.Models.Room", b =>
                {
                    b.HasOne("StaySimple.HotelService.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("StaySimple.HotelService.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
